apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: spx-options-trading-bot-development

namespace: spx-options-dev

resources:
  - ../../base

commonLabels:
  env: development
  tier: trading

images:
  - name: spxoptionsregistry.azurecr.io/spx-options-trading-bot
    newTag: dev-latest

replicas:
  - name: spx-options-trading-bot
    count: 1

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: spx-options-trading-bot
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "development"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "1Gi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "500m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "512Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "250m"

  - target:
      group: autoscaling
      version: v2
      kind: HorizontalPodAutoscaler
      name: spx-options-trading-bot-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3

configMapGenerator:
  - name: spx-options-config
    behavior: merge
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=DEBUG
      - DEBUG=true
      - METRICS_ENABLED=true
      - TRADING_ENABLED=false
      - MAX_POSITIONS=5
