apiVersion: v1
kind: Secret
metadata:
  name: spx-options-secrets
  labels:
    app: spx-options-trading-bot
    tier: trading
    component: secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  # Use: echo -n "your-secret-value" | base64
  redis-url: cmVkaXM6Ly9zcHgtcmVkaXMtc2VydmljZTo2Mzc5  # redis://spx-redis-service:6379
  database-url: cG9zdGdyZXNxbDovL3RyYWRpbmdfdXNlcjpwYXNzd29yZEBzcHgtcG9zdGdyZXMtc2VydmljZTo1NDMyL3RyYWRpbmdfZGI=  # postgresql://trading_user:password@spx-postgres-service:5432/trading_db
  api-key: eW91ci1hcGkta2V5LWhlcmU=  # your-api-key-here
  trading-api-key: eW91ci10cmFkaW5nLWFwaS1rZXktaGVyZQ==  # your-trading-api-key-here
  market-data-api-key: eW91ci1tYXJrZXQtZGF0YS1hcGkta2V5LWhlcmU=  # your-market-data-api-key-here

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spx-options-trading-bot
  labels:
    app: spx-options-trading-bot
    tier: trading
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spx-options-trading-bot-role
  labels:
    app: spx-options-trading-bot
    tier: trading
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spx-options-trading-bot-binding
  labels:
    app: spx-options-trading-bot
    tier: trading
subjects:
  - kind: ServiceAccount
    name: spx-options-trading-bot
    namespace: default  # This will be overridden by kustomize
roleRef:
  kind: Role
  name: spx-options-trading-bot-role
  apiGroup: rbac.authorization.k8s.io
